### ISSUE TITLE
element怎么样处理会像下面链接给出的效果一样。

### ISSUE THREAD

**Issue by wangyongchao123** [coldfix/madx-dummy#112]
date: 2011.11.23
In nov16q.txt I try to match the periodic line CELL such that mux has the desired value, and that betx and bety at the end are equal, whatever their value beta, which is also variable. I see that beta does not get varied, the matching does not reach the specified tolerance, and this is my problem. I know that a solution exists. I can ask for both cell tunes, observe the difference (betx-bety), and calculate the vertical cell tune that brings me closer to the solution.

I now know that MAD8 solved a similar problem in 2006. The data are in jun17c.txt

**Comment by coldfix** [comment]
**Originally by _ldeniau_ on 2012-01-30 15:22:53 +0100**

___
**Attachment added:** [`nov16h.txt`](https://raw.githubusercontent.com/coldfix/madx-tickets/master/attachments/112/nov16h.txt) (6.8 KiB)

**Comment by coldfix** [comment]
**Originally by _ldeniau_ on 2012-01-30 15:23:02 +0100**

___
**Attachment added:** [`jun17c.txt`](https://raw.githubusercontent.com/coldfix/madx-tickets/master/attachments/112/jun17c.txt) (2.8 KiB)

**Comment by coldfix** [comment]
**Originally by _ldeniau_ on 2012-01-30 16:07:05 +0100**

___
date: 2011.11.25, R. De Maria
For some reason (speed?) the old mad8 functionality has not been implemented. For this and other reasons few years ago I introduced in the code an (ugly) matching mode that is more verbose but more flexible that solves your problem.
See the example below, I hope it helps...

use,period=rcell;
rfk1=fk1;
rdk1=dk1;
match,use_macro;
vary,name=rfk1,step=0.1;
vary,name=rdk1,step=0.1;
m1: macro={  twiss;   };
constraint,expr= table(twiss,rcell$end,betx)=table(twiss,rcell$end,bety);
constraint,expr= table(twiss,rcell$end,mux)=1/4;
jacobian,calls=10,tolerance=1e-20;
endmatch;

MATCH SUMMARY

--------------------------------------------------------------------
macro: m1                  
 constraint: table(twiss,rcell$end,betx)=table(twiss,rcell$end,bety)
 values:     +3.02264e+00=+3.02264e+00
 weight:     +1.00000e+00
 penalty:    -1.51879e-13

 constraint: table(twiss,rcell$end,mux)=1/4          
 values:     +2.50000e-01=+2.50000e-01
 weight:     +1.00000e+00
 penalty:    +1.11022e-16

Final Penalty Function =   2.30670941e-26
